kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: snucse-project
  name: wiki-search-engine-pvc
spec:
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: wiki-search-engine-snapshot
  accessModes:
    - ReadOnlyMany
  storageClassName: premium-rwo
  resources:
    requests:
      storage: 30Gi