apiVersion: v1
kind: Namespace
metadata:
  name: snucse-project
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-search-engine
  namespace: default
  labels:
    app: wiki-search-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wiki-search-engine
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      name: wiki-search-engine
      namespace: default
      labels:
        app: wiki-search-engine
    spec:
      containers:
        - image: REGISTRY/PROJECT_ID/IMAGE:TAG
          name: wiki-search-server
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: wiki-search-engine
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: wiki-search-engine
  ports:
    - port: 3000
      targetPort: 3000
