apiVersion: v1
kind: Namespace
metadata:
  name: snucse-project
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-search-engine
  namespace: default
  labels:
    app: wiki-search-engine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wiki-search-engine
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      name: wiki-search-engine
      namespace: default
      labels:
        app: wiki-search-engine
    spec:
      containers:
        - name: wiki-search-server
          image: REGISTRY/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /tmp/data
              name: wiki-search-engine-volume
              readOnly: true
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "./startup.sh"]
          # resources:
          #   requests:
          #     memory: "2.5Gi"
          #     cpu: "750m"
          #   limits:
          #     memory: "2.5Gi"
          #     cpu: "750m"
      volumes:
        - name: wiki-search-engine-volume
          persistentVolumeClaim:
            claimName: wiki-search-engine-pvc
            readOnly: true
            
---
apiVersion: v1
kind: Service
metadata:
  name: wiki-search-engine
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: wiki-search-engine
  ports:
    - port: 3000
      targetPort: 3000
