name: CI/CD

on:
  push:
    branches: [ server-DS, main ]

defaults:
  run:
    working-directory: ./node

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_DEV }}
  IMAGE: wiki-search-engine
  REGISTRY: gcr.io

jobs:
  deploy:
      name: CI/CD
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [14.x]

      steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY_DEV }}
          project_id: ${{ secrets.GCP_PROJECT_ID_DEV }}

      - name: Google Cloud auth for configure-docker
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_REGION }}
          credentials: ${{ secrets.GCP_SA_KEY_DEV }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: npm install, build, test
        run: |-
          npm ci --silent
          npm run build --if-present
          npm test

      - name: Build the Docker image
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      - name: Push the Docker image to Google Artifact Registry
        run: |-
          docker push "$REGISTRY/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy the Docker image to the GKE cluster
        run: |-
          # replacing the image name in the k8s template
          ./kustomize edit set image $REGISTRY/$PROJECT_ID/$IMAGE:v1=$REGISTRY/$PROJECT_ID/$IMAGE:$GITHUB_SHA
          ./kustomize build . | kubectl apply -f -